export const STROOPS_PER_TOKEN = 10_000_000
export const MIN_CONTRACT_AMOUNT = 1 / STROOPS_PER_TOKEN
export const MAX_CONTRACT_AMOUNT = Number.MAX_SAFE_INTEGER / STROOPS_PER_TOKEN

export const MIN_FIAT_AMOUNT = 1
export const MAX_FIAT_AMOUNT = 100_000
